name: Deploy Node.js to EC2

on:
  push:
    branches:
      - main # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Copy code and deploy to EC2
      - name: Copy code to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/enchant-courier
            git pull origin main
            npm install
            pm2 restart nodejsapp || pm2 start server.js --name nodejsapp
            pm2 save

      # 3️⃣ Notify Lambda about workflow status
      - name: Notify Lambda about workflow status
        if: always() # ensures it runs even if previous steps fail
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://mfulvipgt4.execute-api.ap-southeast-2.amazonaws.com/prod/notify
          method: POST
          contentType: "application/json"
          data: |
            {
            "workflow_name": "${{ github.workflow }}",
            "status": "${{ job.status }}",
            "repository": "${{ github.repository }}",
            "actor": "${{ github.actor }}"
            }

# test